spring:
  application:
    name: userservice

server:
  port: 0
  context-path: /userservice/v1
  display-name: userservice

logging:
  level:
    org.springframework: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      instanceId:
        ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}